version: "3.1"

services:


  broker:
    image: rabbitmq:3.8
    container_name: broker_host
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app:
    build: .
    depends_on:
      - broker
    environment:
      - rabbitmq=broker
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge
